title: Экзаменационные билеты
description: Расписанные билеты к экзамену с математическими формулами
baseurl: "/math-exam" # Имя вашего репозитория
url: "" # Базовый URL вашего сайта

# Добавляем настройки для главной страницы
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "index.md"
    values:
      layout: "home"

# Настройки темы
theme: minima

# Настройки Markdown
markdown: kramdown
kramdown:
  math_engine: katex
  math_engine_opts:
    preview: true

# Плагины
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-math-katex

# Настройки GitHub Pages
github: [metadata]
safe: true
lsi: false
increment_posts: false
